# Generated by Django 5.2.8 on 2025-12-12 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securityevent',
            name='api_securit_threat__8b5f2a_idx',
        ),
        migrations.AddField(
            model_name='securityevent',
            name='threat_type',
            field=models.CharField(choices=[('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS'), ('brute_force', 'Brute Force'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('ransomware', 'Ransomware'), ('data_breach', 'Data Breach')], default='malware', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='action_taken',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='geo_country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='protocol',
            field=models.CharField(blank=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uploadedcsvfile'),
        ),
        migrations.AlterField(
            model_name='uploadedcsvfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['threat_type'], name='api_securit_threat__d45cb4_idx'),
        ),
    ]
